CREATE TABLE IF NOT EXISTS `contas_integracao_lotes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tipo` enum('pagar','receber') NOT NULL,
  `status` enum('rascunho','processando','concluido','concluido_com_erros','erro','cancelado') NOT NULL DEFAULT 'rascunho',
  `total_itens` int(11) NOT NULL DEFAULT 0,
  `total_enviados` int(11) NOT NULL DEFAULT 0,
  `total_erros` int(11) NOT NULL DEFAULT 0,
  `payload_json` longtext DEFAULT NULL,
  `erro_mensagem` text DEFAULT NULL,
  `criado_por` int(11) DEFAULT NULL,
  `enviado_em` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_contas_lotes_tipo_status` (`tipo`,`status`),
  KEY `idx_contas_lotes_criado_por` (`criado_por`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `contas_integracoes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `lote_id` bigint(20) unsigned DEFAULT NULL,
  `tipo` enum('pagar','receber') NOT NULL,
  `origem_tabela` varchar(80) NOT NULL,
  `origem_id` bigint(20) unsigned NOT NULL,
  `origem_ref` varchar(120) DEFAULT NULL,
  `destino_banco` varchar(80) NOT NULL DEFAULT 'contas_agrocolitti',
  `destino_tabela` varchar(80) NOT NULL DEFAULT 'lancamentos',
  `destino_id` bigint(20) unsigned DEFAULT NULL,
  `status` enum('pendente','preparado','enviado','erro','ignorado','cancelado') NOT NULL DEFAULT 'pendente',
  `ndocumento` varchar(80) DEFAULT NULL,
  `fornecedor_nome` varchar(255) DEFAULT NULL,
  `cnpj` varchar(32) DEFAULT NULL,
  `dataemissao` date DEFAULT NULL,
  `vencimento` date DEFAULT NULL,
  `competencia` varchar(7) DEFAULT NULL,
  `valor` decimal(12,2) NOT NULL DEFAULT 0.00,
  `desconto_funrural` decimal(12,2) NOT NULL DEFAULT 0.00,
  `desconto_devolucao` decimal(12,2) NOT NULL DEFAULT 0.00,
  `desconto_total` decimal(12,2) NOT NULL DEFAULT 0.00,
  `valortotal` decimal(12,2) NOT NULL DEFAULT 0.00,
  `payload_json` longtext DEFAULT NULL,
  `erro_mensagem` text DEFAULT NULL,
  `criado_por` int(11) DEFAULT NULL,
  `enviado_por` int(11) DEFAULT NULL,
  `enviado_em` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_contas_integracoes_origem` (`tipo`,`origem_tabela`,`origem_id`),
  KEY `idx_contas_integracoes_lote` (`lote_id`),
  KEY `idx_contas_integracoes_status` (`tipo`,`status`),
  KEY `idx_contas_integracoes_destino` (`destino_banco`,`destino_tabela`,`destino_id`),
  KEY `idx_contas_integracoes_documento` (`ndocumento`,`cnpj`),
  CONSTRAINT `fk_contas_integracoes_lote` FOREIGN KEY (`lote_id`) REFERENCES `contas_integracao_lotes` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `contas_integracao_eventos` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `integracao_id` bigint(20) unsigned DEFAULT NULL,
  `lote_id` bigint(20) unsigned DEFAULT NULL,
  `evento` varchar(80) NOT NULL,
  `detalhe` text DEFAULT NULL,
  `payload_json` longtext DEFAULT NULL,
  `usuario_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_contas_eventos_integracao` (`integracao_id`),
  KEY `idx_contas_eventos_lote` (`lote_id`),
  KEY `idx_contas_eventos_evento` (`evento`),
  CONSTRAINT `fk_contas_eventos_integracao` FOREIGN KEY (`integracao_id`) REFERENCES `contas_integracoes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_contas_eventos_lote` FOREIGN KEY (`lote_id`) REFERENCES `contas_integracao_lotes` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
